apiVersion: v1
kind: Service
metadata:
  name: data-uid-{{ .Values.environment }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: data-uid-{{ .Values.environment }}
  ports:
    - port: {{ .Values.dataui.port }}
      name: http
      targetPort: 8080
      nodePort: {{ .Values.dataui.nodePort }}
    - port: {{ .Values.swankServer.port }}
      name: swank
      targetPort: 4005
      nodePort: {{ .Values.swankServer.nodePort }}
